services:
  oapi-generator:
    build:
      context: .
      dockerfile: ./docker/oapi.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command:
      - "-package"
      - "oapi"
      - "-generate"
      - "types,client"
      - "-o"
      - "./client/oapi/client.go"
      - "./api/test_api.json"

  openapi-generator:
    build:
      context: .
      dockerfile: ./docker/openapi.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: >
      generate -i ./api/test_api.json 
      -g go 
      -o ./client/openapi 
      --additional-properties=packageName=openapi

  hoverfly:
    image: spectolabs/hoverfly:v1.6.0
    ports:
      - "8500:8500"
      - "8888:8888"
    command: [-webserver]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api/v2/hoverfly"]
      interval: 1s
      timeout: 3s
      retries: 60

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - HTTP_PROXY=http://hoverfly:8500
      - HTTPS_PROXY=http://hoverfly:8500
      - CAPTURE_MODE=${CAPTURE_MODE:-false}
    depends_on:
      hoverfly:
        condition: service_healthy