version: 3

tasks:
  build:
    desc: "Build the project"
    cmds:
      - go build -v -i main.go

  generate:
    desc: "Generate the project"
    cmds:
      - docker-compose run --rm oapi-generator

  generate-openapi:
    desc: "Generate the openapi"
    cmds:
      - docker-compose run --rm openapi-generator